{
 "title": "Henhouse monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Humidity Min Value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min_over_time(humidity_percent[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity Mean Value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(humidity_percent[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity Max Value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(humidity_percent[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity Last Value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "humidity_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature Min Value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min_over_time(temperature_celsius[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Mean Value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(temperature_celsius[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Max Value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(temperature_celsius[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Last Value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time(temperature_celsius[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity (Percent)",
   "type": "timeseries",
   "description": "Display the humidity in percent over the time.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "humidity_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature (Celsius)",
   "type": "timeseries",
   "description": "Display the temperature in celsius over time.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    { "expr": "temperature_celsius", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Humidity (Percent) table",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "humidity_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature (Celsius) table",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "temperature_celsius", "legendFormat": "__auto" }
   ]
  }
 ]
}